"""empty message

Revision ID: 870c259541ec
Revises: 
Create Date: 2025-05-18 11:54:50.387784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870c259541ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_grounded', sa.Boolean(), nullable=True),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot')
    op.drop_table('aircraft')
    op.drop_table('fleet')
    op.drop_table('company_financial')
    # ### end Alembic commands ###
